title: Плагины
icon: ph:puzzle-piece
navigation:
  - { title: Обзор, icon: ph:info, to: /ru/plugins }
  - { title: Создание плагинов, icon: ph:code, to: /ru/plugins/creating-plugins }
  - { title: API плагинов, icon: ph:brackets-curly, to: /ru/plugins/plugin-api }
  - { title: Примеры плагинов, icon: ph:lightbulb, to: /ru/plugins/plugin-examples }
  - { title: Публикация плагинов, icon: ph:upload, to: /ru/plugins/publishing-plugins }
  # Пример критически важного неактивного пункта
  - { title: Маркетплейс плагинов, icon: ph:shopping-cart, status: critical }
  # Пример некритичного неактивного пункта
  - { title: Система рейтингов плагинов, icon: ph:star, status: planned }